name: Create v1.0.2 Release

on:
  workflow_dispatch:

jobs:
  create-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v1.0.2
          release_name: v1.0.2
          draft: false
          prerelease: false
          body: |
            ## v1.0.2 – 2025-08-12

            ### Fixed
            - Branch validation now works in GitHub Actions environments where local branches may not exist after checkout
            - Fallback to remote branch and fetch if local branch is missing
            - All error messages and documentation use direct, factual language as per project guidelines
            - Tests updated for new validation logic

            This release addresses errors where GitHub Actions failed with 'Branch does not exist' due to missing local refs after checkout. All users should update to v1.0.2 for reliable CI/CD operation.